# -*- coding: utf-8 -*-
"""DM_HW_1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTW2weYYxqIbNlhnMkpzhwYU_lk7BMXv
"""  
# written and executed by Vignesh Prabhakar ( USC ID : 4024890667)

import pandas as pd
import numpy as np
import requests
import json
import sys

g1 = requests.get('https://project-one-150405.firebaseio.com/sno.json')
list_g1 =g1.json()


g2 = requests.get('https://project-one-150405.firebaseio.com/name.json')
list_g2 =g2.json()



g3 = requests.get('https://project-one-150405.firebaseio.com/sc.json')
list_g3 =g3.json()

g4 = requests.get('https://project-one-150405.firebaseio.com/reverse_index/index.json')
ri=g4.json()

dict1 = {list_g1[i]:{"facility_name":list_g2[i],"score": list_g3[i]} for i in range(len(list_g2))}

inp = sys.argv[1]
inp=inp.lower()
tokenize = []

tokenize = inp.split()



search_list=[]
for i in tokenize :
  for j in ri.keys() :
    if(i==j):
      search_list.append(ri[i])

di={}
for i in range(0,len(search_list)):
  for j in range(0,len(search_list[i])):
     di[search_list[i][j]] = dict1[search_list[i][j]]
            
print(json.dumps(di,indent=4))

