# -*- coding: utf-8 -*-
"""DM_HW_3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13DWR6FGRMBZfcQrxHuG2tg9gaF6XuWPq
"""

from lxml import etree
import re
import string
import sys

fd = open(sys.argv[1])
fd1 = open(sys.argv[2])
tree = etree.parse(fd)
tree1 = etree.parse(fd1)
word =sys.argv[3]
word =word.lower()
sp=word.split()
xml1='<?xml version="1.0" encoding="UTF-8" ?>\n<results>\n'
flag=0
star=0
for el in tree1.xpath('//keyword'):
  txt1=el.find('book/*').text
  if(all(map(lambda w: w in txt1.lower() ,sp))):
    star=1
    

class Dictionarylist(dict):
    def __setitem__(self, key, value):
        try:
            self[key]
        except KeyError:
            super(Dictionarylist, self).__setitem__(key, [])
        self[key].append(value)
        
d1 = Dictionarylist()
for i in sp:
  for t in tree1.xpath('//keyword'):    
    if(t.attrib['content'].lower()==i.lower()):
      att=t.find('book[@id]').attrib
      att=str(att.values())
      att=re.sub('['+string.punctuation +']', '', att)
      txt=t.find('book/*').text
      tag=t.find('book/*').tag
      
      if(all(map(lambda w: w in txt.lower() ,sp))):
        flag=2
        d1[att]={tag:txt}
      
      elif(star==0):
        flag=1
        d1[att]={tag:txt}
        
    



for x in d1.keys():
  xml1=xml1+ '<book id="'+x+'">\n'
  lst=""
  for y in range(0,len(d1[x])):
    for z in d1[x][y].keys():
      if(lst!=z):
        xml1=xml1+'<'+z+'>\n'+d1[x][y][z]+'.\n</'+z+'>\n'
      lst=z
  
  xml1=xml1+'</book>\n'

if(flag==2):
  xml1=xml1+'</results>\n'
  file = open(sys.argv[4], "w")
  file.write("%s" % xml1)
  file.close()
elif(flag==1):
  xml2=xml1+'<book/>\n'+'</results>\n'
  file = open(sys.argv[4], "w")
  file.write("%s" % xml2)
  file.close()  
else:
  xml2 ='<?xml version="1.0" encoding="UTF-8" ?>\n<results/>\n'
  file = open(sys.argv[4], "w")
  file.write("%s" % xml2)
  file.close()
