# -*- coding: utf-8 -*-
"""DM_HW_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnCIL99sav8A-EEagTLYhBTIpy4Ko9fV
"""
# Written and executed by Vignesh Prabhakar ( USC ID : 4024890667)

import pandas as pd
import numpy as np
import requests
import json
import sys
import re

url1 ='https://project-one-150405.firebaseio.com/sno.json'
url2 ='https://project-one-150405.firebaseio.com/name.json'
url3 ='https://project-one-150405.firebaseio.com/sc.json'

df =pd.read_csv(sys.argv[1])

serial_no = df["serial_number"]
facility_name =df["facility_name"]
score = df["score"]


serialno_dict = serial_no.to_dict()
facilityname_dict = facility_name.to_dict()
score_dict = score.to_dict()

serialno =  json.dumps(serialno_dict)
facilityname =json.dumps(facilityname_dict)
score1 = json.dumps(score_dict) 

r = requests.put(url1,data=serialno)
r1 = requests.put(url2,data=facilityname)
r2 = requests.put(url3,data=score1)

g1 = requests.get('https://project-one-150405.firebaseio.com/name.json')
list_g1 =g1.json()

first_split = []

for i in list_g1:

    first_split.append(i.split())

    
    


g2 = requests.get('https://project-one-150405.firebaseio.com/sno.json')
list_g2 =g2.json()

class Dictionarylist(dict):
    def __setitem__(self, key, value):
        try:
            self[key]
        except KeyError:
            super(Dictionarylist, self).__setitem__(key, [])
        self[key].append(value)


d = Dictionarylist()
for i in range(0,len(first_split)):
  for j in range(0,len(first_split[i])):
      first_split[i][j]=re.sub(r'[^a-zA-Z0-9_\s]+', ' ',first_split[i][j] )
      d[first_split[i][j]] = list_g2[i]


d =  {k.lower(): v for k, v in d.items()}
final_dict = {"index":d}
sent = json.dumps(final_dict)

url_wrt ='https://project-one-150405.firebaseio.com/reverse_index.json'
reverse_index = requests.put(url_wrt,data=sent)

print(json.dumps(reverse_index.json(), indent=4))

